In [21]:
import numpy as np

matriz = np.linspace(1, 30, 30)

In [17]:
matriz


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.])

In [62]:
matrix = matriz.reshape((6, 5))
matrix


array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.],
       [26., 27., 28., 29., 30.]])

In [59]:
matriz_azul = matrix[2:4 ,0:2 ]
matriz_azul

array([[11., 12.],
       [16., 17.]])

In [61]:
matriz_roja = matrix[[0, 4, 5], 3:]
matriz_roja

array([[ 4.,  5.],
       [24., 25.],
       [29., 30.]])

In [60]:
matriz_verde = matrix[[0, 1, 2, 3], [1, 2, 3, 4]]
matriz_verde

array([ 2.,  8., 14., 20.])