In [20]:
import numpy as np

matriz = np.array([[0, 1, 2, 3, 4, 5], [10, 11, 12, 13, 14, 15], [20, 21, 22, 23, 24, 25], [30, 31, 32, 33, 34, 35], [40, 41, 42, 43, 44, 45], [50, 51, 52, 53, 54, 55]])
                   
matriz

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [25]:
matriz_naranja = matrix[0 ,3:5 ]
matriz_naranja




array([3, 4])

In [26]:
matriz_roja = matrix[0:5 ,2 ]
matriz_roja

array([ 2, 12, 22, 32, 42])

In [27]:
matriz_aguamarina = matrix[4: , 4: ]
matriz_aguamarina

array([[44, 45],
       [54, 55]])

In [28]:
matriz_verde = matrix[2::2 , 0::2 ]
matriz_verde

array([[20, 22, 24],
       [40, 42, 44]])