In [1]:
import numpy as np

matriz = np.array([[0, 1, 2, 3, 4, 5], [10, 11, 12, 13, 14, 15], [20, 21, 22, 23, 24, 25], [30, 31, 32, 33, 34, 35], [40, 41, 42, 43, 44, 45], [50, 51, 52, 53, 54, 55]])
                   
matriz   

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [3]:
matriz_rrojo = matriz[(0, 2, 5) , 2]
matriz_rrojo

array([ 2, 22, 52])

In [4]:
matriz_nnaranja = matriz[(0, 1, 2, 3, 4) ,(1, 2, 3, 4, 5)]
matriz_nnaranja

array([ 1, 12, 23, 34, 45])

In [5]:
matriz_aazulaguamarina = matriz[3: , (0, 2, 5) ]
matriz_aazulaguamarina 

array([[30, 32, 35],
       [40, 42, 45],
       [50, 52, 55]])