In [11]:
import numpy as np



In [12]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)

In [13]:
a


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [20]:
np.vstack((a, b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])