In [7]:
import numpy as np

a = np.array([1, 2, 3])

In [8]:
a


array([1, 2, 3])

In [11]:
c = np.tile((a),(3))
c

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [12]:
b = a.repeat(3)
b



array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [19]:
def concatenar (arr1, arr2):
    return np.concatenate((arr1, arr2))



In [20]:
concatenar(b, c)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])