In [7]:
import numpy as np

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [8]:
a

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

In [9]:
b

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

In [31]:
np.intersect1d(a, b)

array([2, 4])