In [1]:
import numpy as np

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [2]:
a

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

In [3]:
b

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

In [4]:
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)