In [3]:
import numpy as np

In [8]:
#Crear la matriz, en este caso definiré fila por fila para luego unirlas mediante la función vstack
print("MATRIZ ORIGINAL 2")
a = np.arange(6)
b = np.arange(10,16)
c = np.arange(20,26)
d = np.arange(30,36)
e = np.arange(40,46)
f = np.arange(50,56)
Matriz = np.vstack((a,b,c,d,e,f))
print(Matriz)
print()

#Para esta matriz nuevamente haré uso de la función hstack
print("MATRIZ NARANJA")
A = Matriz[0,1]
B = Matriz[1,2]
C = Matriz[2,3]
D = Matriz[3,4]
E = Matriz[4,5]
print(np.hstack((A,B,C,D,E)))
print()

#En esta matriz utilizaré vstack
print("MATRIZ ROJA")
F = Matriz[0,2]
G = Matriz[2,2]
H = Matriz[5,2]
print(np.vstack((F,G,H)))
print()

#En esta ultima agruparé las entradas en grupos de 3 y luego usaré hstack para agruparlas
print("MATRIZ AZUL")
I = Matriz[3:6,0].reshape(3,1)
J = Matriz[3:6,2].reshape(3,1)
K = Matriz[3:6,5].reshape(3,1)
print(np.hstack((I,J,K)))
Matriz[[1,0],[2,1]]

MATRIZ ORIGINAL 2
[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]

MATRIZ NARANJA
[ 1 12 23 34 45]

MATRIZ ROJA
[[ 2]
 [22]
 [52]]

MATRIZ AZUL
[[30 32 35]
 [40 42 45]
 [50 52 55]]


array([12,  1])