In [2]:
import numpy as np

In [8]:
#Crear un vector con los valores de 1 a 30 mediante la función arange() y redistribuir dichos valores formando una matriz de 6x5 usando la función reshape()
print("MATRIZ ORIGINAL 1")
Matriz = np.arange(1,31).reshape(6,5)

#obtener submatrices usando slicing, se debe tener en cuenta que termina una columna o fila antes de la indicada
print(Matriz)
print()

#Matriz azul
print("MATRIZ AZUL")
print(Matriz[2:4,0:2])
print()

#Matriz roja: Para esta matriz utilizaré la función vstack ya que una de las filas esta separada de la otra
print("MATRIZ ROJA")
a = Matriz[0,3:5]
b = Matriz[4:6,3:5]
print(np.vstack((a,b)))
print()

#Matriz verde: En este caso utilizaré la función hstack con el fin de apilar las matrices de manera horizontal
print("MATRIZ VERDE")
a = Matriz[0,1]
b = Matriz[1,2]
c = Matriz[2,3]
d = Matriz[3,4]
print(np.hstack((a,b,c,d)))

MATRIZ ORIGINAL 1
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]

MATRIZ AZUL
[[11 12]
 [16 17]]

MATRIZ ROJA
[[ 4  5]
 [24 25]
 [29 30]]

MATRIZ VERDE
[ 2  8 14 20]
