In [1]:
import numpy as np

In [38]:
#Crear la matriz, en este caso definiré fila por fila para luego unirlas mediante la función vstack
print("MATRIZ ORIGINAL 2")
a = np.arange(6)
b = np.arange(10,16)
c = np.arange(20,26)
d = np.arange(30,36)
e = np.arange(40,46)
f = np.arange(50,56)
Matriz = np.vstack((a,b,c,d,e,f))
print(Matriz)
print()

print("MATRIZ ROJA")
M = Matriz[0:6,2]
print(M.reshape(6,1))
print()

print("MATRIZ NARANJA")
print(Matriz[0,3:5])
print()


#Para la siguiente matriz decidí obtener entrada por entrada con el fin de luego agrupar las filas con hstack y finalmente agrupar toda la matriz con vstack
print("MATRIZ VERDE")
A = Matriz[2,0]
B = Matriz[2,2]
C = Matriz[2,4]
D = Matriz[4,0]
E = Matriz[4,2]
F = Matriz[4,4]
ABC = np.hstack((A,B,C))
DEF = np.hstack((D,E,F))
print(np.vstack((ABC,DEF)))
print()

print("MATRIZ AZUL")
print(Matriz[4:6,4:6])


MATRIZ ORIGINAL 2
[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]

MATRIZ ROJA
[[ 2]
 [12]
 [22]
 [32]
 [42]
 [52]]

MATRIZ NARANJA
[3 4]

MATRIZ VERDE
[[20 22 24]
 [40 42 44]]

MATRIZ AZUL
[[44 45]
 [54 55]]
