## Matriz identidad:
> Se puede crear una matriz identidad con la función `eye` y pasando a esta un `integer`. Esto devuelve una matriz cuadrada de esa dimensión con `unos` en la diagonal y en los demás campos es `cero`. Su determinante es 1

In [1]:
import numpy as np

In [3]:
matriz_identidad = np.eye(4)
matriz_identidad

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
# Esta matriz no hace ninguna modificación. Es un elemento neutro
vector = np.array([1, 2, 3, 4])
vector_dos = np.array([[10], [3], [4], [6]])
# hacer producto punto con .dor
matriz_identidad.dot(vector)

array([1., 2., 3., 4.])

In [8]:
matriz_identidad.dot(vector_dos)

array([[10.],
       [ 3.],
       [ 4.],
       [ 6.]])

## Matriz Inversa:
Existe una matriz que al multiplicarla por otra, me devuelve la identidad. Cuando la multiplicación entre matrices da como resultado la matriz identidad, es porque estoy multiplicando mi matriz por su inversa
> `Ax = b`. Ahora podría usar `x = b * A-1`

In [9]:
matriz = np.array([[1, 2, 4], [4 , 7, 8], [7, 2, 3]])
matriz

array([[1, 2, 4],
       [4, 7, 8],
       [7, 2, 3]])

In [10]:
# para calcular la inversa con Numpy, uso linalg.inv()
inversa = np.linalg.inv(matriz)
inversa

array([[-0.07042254, -0.02816901,  0.16901408],
       [-0.61971831,  0.35211268, -0.11267606],
       [ 0.57746479, -0.16901408,  0.01408451]])

In [11]:
matriz.dot(inversa)

array([[ 1.00000000e+00,  0.00000000e+00,  6.93889390e-18],
       [ 0.00000000e+00,  1.00000000e+00,  8.32667268e-17],
       [ 0.00000000e+00, -2.77555756e-17,  1.00000000e+00]])

# Matriz singular
Cuando una matriz no tiene inversa, tengo la matriz singular. Una matriz no tiene inversa cuando su determinante es cero

> Toda matriz que no es cuadrada es singular

In [12]:
singular = np.array([[1, 1], [1, 1]])

In [14]:
np.linalg.inv(singular)

LinAlgError: Singular matrix

In [15]:
# le puedo decir a Numpy que números cercanos a cero los muestre como cero
np.set_printoptions(suppress=True)

In [16]:
# 3x + y = 1
# 2x + y = 1
A = np.array([[3, 1], [2, 1]])
b = np.array([1, 1])

In [17]:
inversa_A = np.linalg.inv(A)
inversa_A

array([[ 1., -1.],
       [-2.,  3.]])

In [19]:
x = inversa_A.dot(b)
x

array([0., 1.])

In [20]:
A.dot(x)

array([1., 1.])