In [1]:
import numpy as np

In [2]:
array = np.zeros((3, 2), dtype=np.int32)
array

array([[0, 0],
       [0, 0],
       [0, 0]])

In [3]:
ones = np.ones((2, 4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
# identidad
identidad = np.eye(3, dtype=np.int64)
identidad

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int64)

In [5]:
# matriz de un solo elemento
full = np.full((2, 3), 5.5)
full

array([[5.5, 5.5, 5.5],
       [5.5, 5.5, 5.5]])

In [6]:
np.arange(-5, 6, 0.5)

array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5])

In [7]:
np.linspace(5, 10, 11)

array([ 5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

# COPYING ARRAYS

In [8]:
array

array([[0, 0],
       [0, 0],
       [0, 0]])

In [9]:
array2 = array

In [10]:
array2[0] = 10
array2

array([[10, 10],
       [ 0,  0],
       [ 0,  0]])

In [11]:
array

array([[10, 10],
       [ 0,  0],
       [ 0,  0]])

In [12]:
# the safe way to copy is using the np.copy method
array3 = np.copy(array)
array3

array([[10, 10],
       [ 0,  0],
       [ 0,  0]])

In [13]:
array3[0] = 20
array3

array([[20, 20],
       [ 0,  0],
       [ 0,  0]])

In [14]:
array

array([[10, 10],
       [ 0,  0],
       [ 0,  0]])

# ALGEBRA BASICS

In [15]:
array.T

array([[10,  0,  0],
       [10,  0,  0]])

In [16]:
np.linalg.inv(np.array([[1, 2], [6, 7]]))

array([[-1.4,  0.4],
       [ 1.2, -0.2]])

In [17]:
np.linalg.det(np.array([[1, 2], [6, 7]]))

-5.000000000000001

In [18]:
diag = np.diag([[1, 2], [6, 7]])
diag

array([1, 7])

In [19]:
np.diag(diag)

array([[1, 0],
       [0, 7]])

# BOOLEAN INDEX (FILTERS)

In [20]:
array

array([[10, 10],
       [ 0,  0],
       [ 0,  0]])

In [21]:
array > 0

array([[ True,  True],
       [False, False],
       [False, False]])

In [22]:
array[array > 0]

array([10, 10])

In [23]:
# conservar las dimensiones con where
# el tecer parametro es el valor default
np.where((array > 0), array, -1)

array([[10, 10],
       [-1, -1],
       [-1, -1]])

In [24]:
array1 = np.array([[1, 2], [0.00000001, 0.00022214520000001]])
array2 = np.array([[1, 2], [0.00000001, 0.00022214520000001]])
array1 == array2

array([[ True,  True],
       [ True,  True]])

In [25]:
np.allclose(array1, array2)

True

# SOLVING LINEAR ECUATIONS

In [26]:
A = np.array([
    [2, 3, 4],
    [5, 3, 7],
    [8, 9, 5],
])
b = np.array([1, 2, 5])

In [27]:
inv = np.linalg.inv(A)
inv

array([[-0.59259259,  0.25925926,  0.11111111],
       [ 0.38271605, -0.27160494,  0.07407407],
       [ 0.25925926,  0.07407407, -0.11111111]])

In [28]:
x = inv.dot(b)

In [29]:
x

array([ 0.48148148,  0.20987654, -0.14814815])

In [35]:
# np.matmul method
np.matmul(inv, b)

array([ 0.48148148,  0.20987654, -0.14814815])

Para realizar le producto punto *la cantidad de columnas del primer array debe ser igual a la cantidad de filas del segundo*

In [36]:
# segunda dimension de la primera matriz igual a la primera dimensión de la segunda matriz
print(inv.shape, b.shape)

(3, 3) (3,)


In [30]:
A.dot(x) == b

array([ True,  True,  True])

In [31]:
x2 = np.linalg.solve(A, b)
x2

array([ 0.48148148,  0.20987654, -0.14814815])

In [32]:
x == x2

array([ True, False, False])

In [33]:
np.allclose(x, x2)

True